### PR TITLE
Add .editorconfig (v1.3.18 from bevry/base)

### PR DESCRIPTION
**Pull request by Zearin**

### CODE REVIEW

**Comment by Zearin** [comment]
Grr @ Travis!  

From the looks of it, PART of the build sees the new commits I added, but it’s still trying to build with the original commit.

@bevry , @balupton: Could you click the Travis “Details” link below and ask Travis to rebuild anyway?  (Should be an option under an icon at the top right)

**Comment by balupton** [comment]
We still must support node 0.8, as about 10% of DocPad users still use it.

Does the latest `.travis.yml` file not fix 0.8 support by auto-updating npm? If not, then there is an issue we must fix.

Perhaps we should add a thing in DocPad to complain to them about 0.8 support, as it is getting a bit behind.

**Comment by Zearin** [comment]
> We still must support node 0.8, as about 10% of DocPad users still use it.

Oh.  Sorry! :(

> Does the latest .travis.yml file not fix 0.8 support by auto-updating npm? If not, then there is an issue we must fix.

Yeah, all the repos with Node 0.8 are complaining about the `^x.x` syntax.

> Perhaps we should add a thing in DocPad to complain to them about 0.8 support, as it is getting a bit behind.

Agreed.  Perhaps a deprecation warning?

**Comment by balupton** [comment]
> Yeah, all the repos with Node 0.8 are complaining about the ^x.x syntax.

Strange as the `npm i -g npm` should fix that. We need to look into this.

> Agreed. Perhaps a deprecation warning?

Yeah, want to send over a pull request in DocPad, the warning can go alongside the code for donation. I  believe DocPad already uses the `semver` package, so it would be something like if `semver.satisifies(process.version, '< 0.10')` then "You're on an old version of Node.js, please upgrade: http://learn.bevry.me/node/install"

**Comment by balupton** [comment]
@Zearin please stop removing 0.8 from travis yml files, we still need that. I'm fine with updating base files in docpad plugins, but don't deviate from the base files if your intent is to update them.

**Pull request closed without merging**
